# ============================================================
#  SonarCloud — Hospital Management System
#  Organisation GitHub : anasxaz
# ============================================================

sonar.projectKey=anasxaz_Hospital-Management-Sys
sonar.organization=anasxaz

sonar.projectName=Hospital Management System - Health Nest
sonar.projectVersion=1.0
sonar.projectDescription=Application de gestion hospitaliere - Projet DevSecOps ENSIAS

# Sources a analyser
sonar.sources=Backend,Frontend/src

# Fichiers a exclure de l'analyse
sonar.exclusions=\
  **/node_modules/**, \
  **/dist/**, \
  **/build/**, \
  **/*.min.js, \
  **/package-lock.json, \
  **/Frontend/public/**

# Fichiers de tests
sonar.tests=Backend/tests

# Encodage
sonar.sourceEncoding=UTF-8

# JavaScript / Node.js
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

# Coverage — rapport lcov généré par c8 (remédiation DevSecOps)
sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info
